import { supabase } from "@/integrations/supabase/client";
import { sendPushToDevice } from "@/hooks/useNotifications";
import { checkFeatureEnabled } from "@/lib/featureFlags";

// Map automation event names to feature flag module names
const EVENT_TO_MODULE: Record<string, string> = {
  interview_scheduled: "smart_scheduling",
  interview_rescheduled: "smart_scheduling",
  candidate_approved: "automated_evaluation",
  new_job_opened: "talent_pool",
  document_pending: "auto_notifications",
  score_below_minimum: "automated_evaluation",
  no_show_detected: "smart_scheduling",
  process_closed: "auto_notifications",
  talent_pool_match: "talent_pool",
};

/**
 * Evaluate a simple condition_json against a payload.
 */
function evaluateCondition(condition: Record<string, any>, payload: Record<string, any>): boolean {
  const keys = Object.keys(condition);
  if (keys.length === 0) return true;
  return keys.every((k) => {
    const condValue = condition[k];
    const payloadValue = payload[k];

    // Support advanced operators generated by AutomationRuleBuilder
    if (condValue && typeof condValue === "object" && !Array.isArray(condValue)) {
      if ("$not_equals" in condValue) return payloadValue !== condValue.$not_equals;
      if ("$greater_than" in condValue) return Number(payloadValue) > Number(condValue.$greater_than);
      if ("$less_than" in condValue) return Number(payloadValue) < Number(condValue.$less_than);
      if ("$contains" in condValue) return String(payloadValue ?? "").toLowerCase().includes(String(condValue.$contains).toLowerCase());
    }

    // Default: strict equality
    return payloadValue === condValue;
  });
}

/** Sleep helper for exponential backoff */
function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Insert an activity_logs row stamped with the current user.
 * RLS policy requires `user_id = auth.uid()`; sem isso o insert volta 403.
 */
async function logActivity(row: { action: string; module: string; details?: Record<string, any> }) {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user?.id) return; // sem sessão, não loga (evita 403)
  const { error } = await supabase.from("activity_logs").insert({
    user_id: user.id,
    action: row.action,
    module: row.module,
    details: row.details ?? {},
  } as any);
  if (error) console.warn(`[AuditLog] ${row.action} failed:`, error.message);
}


interface AutomationConfig {
  automation_enabled: boolean;
  max_automation_retries: number;
  automation_timeout_seconds: number;
  allow_ai_in_automation: boolean;
}

async function getAutomationConfig(): Promise<AutomationConfig> {
  const { data } = await supabase
    .from("global_settings")
    .select("key, value")
    .eq("category", "automations")
    .in("key", ["automation_enabled", "max_automation_retries", "automation_timeout_seconds", "allow_ai_in_automation"]);

  const map: Record<string, any> = {};
  (data ?? []).forEach((s: any) => { map[s.key] = s.value; });

  return {
    automation_enabled: map.automation_enabled !== false,
    max_automation_retries: Number(map.max_automation_retries) || 3,
    automation_timeout_seconds: Number(map.automation_timeout_seconds) || 30,
    allow_ai_in_automation: map.allow_ai_in_automation !== false,
  };
}

/** Execute an action with timeout enforcement. */
async function executeActionWithTimeout(
  actionType: string,
  actionPayload: Record<string, any>,
  eventPayload: Record<string, any>,
  timeoutSeconds: number,
  config: AutomationConfig,
): Promise<void> {
  const timeoutMs = timeoutSeconds * 1000;
  const actionPromise = executeAction(actionType, actionPayload, eventPayload, config);

  const timeoutPromise = new Promise<never>((_, reject) =>
    setTimeout(() => reject(new Error(`Timeout: ação "${actionType}" excedeu ${timeoutSeconds}s`)), timeoutMs)
  );

  await Promise.race([actionPromise, timeoutPromise]);
}

/** Execute an action. */
async function executeAction(
  actionType: string,
  actionPayload: Record<string, any>,
  eventPayload: Record<string, any>,
  config: AutomationConfig,
): Promise<void> {
  switch (actionType) {
    case "open_calendar":
      // Register calendar availability for candidate
      if (eventPayload.candidate_id && eventPayload.interview_id) {
        await logActivity({
          action: "calendar_opened_for_candidate",
          module: "automacao",
          details: {
            candidate_id: eventPayload.candidate_id,
            interview_id: eventPayload.interview_id,
            source: "automation",
          },
        });


        // If calendar sync is enabled, invoke Google Calendar sync
        const { data: calSyncSetting } = await supabase
          .from("global_settings")
          .select("value")
          .eq("category", "calendar")
          .eq("key", "calendar_sync_enabled")
          .maybeSingle();

        if (calSyncSetting?.value === true || calSyncSetting?.value === "true") {
          await supabase.functions.invoke("google-calendar-sync", {
            body: {
              interview_id: eventPayload.interview_id,
              candidate_id: eventPayload.candidate_id,
              action: "update",
            },
          }).catch((err) => console.warn("[Automation] Google Calendar sync failed:", err));
        }
      } else {
        console.log("[Automation] Agenda liberada para candidato", eventPayload);
      }
      break;

    case "notify_talent_pool":
      if (eventPayload.unit_job_id) {
        await logActivity({
          action: "talent_pool_notificado",
          module: "automacao",
          details: { unit_job_id: eventPayload.unit_job_id },
        });
      }
      break;


    case "send_reminder":
    case "send_notification": {
      const recipientId = eventPayload.candidate_id || eventPayload.recipient_id;
      if (recipientId) {
        const channel = actionPayload.channel || "push";
        const notifTitle = actionPayload.title || "Lembrete automático";
        const notifBody = actionPayload.body || "Você tem uma pendência no sistema.";

        // Always insert push notification
        await supabase.from("notifications").insert({
          recipient_id: recipientId,
          event_type: actionPayload.event_type || "automation_reminder",
          channel: "push",
          title: notifTitle,
          body: notifBody,
          status: "pending",
          action_url: actionPayload.action_url || "/notificacoes",
          action_type: actionPayload.action_type || "info",
        });

        await sendPushToDevice({
          recipientId,
          title: notifTitle,
          body: notifBody,
        }).catch((err) => console.error("[PUSH] automation push failed:", err));

        // If channel includes whatsapp, also insert whatsapp notification for cascade
        if (channel === "whatsapp" || channel === "all") {
          await supabase.from("notifications").insert({
            recipient_id: recipientId,
            event_type: actionPayload.event_type || "automation_reminder",
            channel: "whatsapp",
            title: notifTitle,
            body: notifBody,
            status: "pending",
            action_url: actionPayload.action_url || "/notificacoes",
            action_type: actionPayload.action_type || "info",
          });
        }
      }
      break;
    }

    case "suggest_content": {
      // Generate educational content via IA and notify candidate
      const candidateId = eventPayload.candidate_id || eventPayload.recipient_id;
      const suggestionType = actionPayload.type || "educational";

      // Invoke IA Edge Function for personalized content
      let educTitle = actionPayload.title || "Conteúdo educativo disponível";
      let educBody = actionPayload.body || "Identificamos áreas para melhoria no seu perfil. Acesse o conteúdo educativo personalizado.";

      try {
        const { data: aiResult } = await supabase.functions.invoke("automation-ai-actions", {
          body: {
            action: "generate_educational_content",
            context: {
              candidate_name: eventPayload.candidate_name || "Candidato",
              error_type: eventPayload.error_type || actionPayload.error_type || "desempenho abaixo do esperado",
              score: eventPayload.score,
              step_title: eventPayload.step_title || actionPayload.step_title,
            },
          },
        });
        if (aiResult?.result?.title) educTitle = aiResult.result.title;
        if (aiResult?.result?.content) educBody = aiResult.result.content;
      } catch (aiError) {
        console.warn("[Automation] IA content generation failed, using fallback:", aiError);
      }

      // Log content suggestion
      await logActivity({
        action: "content_suggestion_generated",
        module: "automacao",
        details: {
          suggestion_type: suggestionType,
          context: eventPayload,
          payload: actionPayload,
          ai_generated: true,
        },
      });


      // Send educational notification to candidate
      if (candidateId) {
        await supabase.from("notifications").insert({
          recipient_id: candidateId,
          event_type: "educational_content",
          channel: "push",
          title: educTitle,
          body: educBody,
          status: "pending",
          action_url: actionPayload.action_url || "/inicio",
          action_type: "info",
          payload: { suggestion_type: suggestionType, score: eventPayload.score },
        } as any);
      }
      break;
    }

    case "block_progression":
      if (eventPayload.application_id) {
        await supabase
          .from("applications")
          .update({ status: "pausado" })
          .eq("id", eventPayload.application_id);
      }
      break;

    case "create_task":
      await logActivity({
        action: actionPayload.task_name || "tarefa_automatica",
        module: "tarefa",
        details: { source: "automation", event: eventPayload, payload: actionPayload },
      });
      break;


    case "trigger_ai_analysis":
      // P1 Guard: check allow_ai_in_automation before executing
      if (!config.allow_ai_in_automation) {
        console.log("[Automation] AI in automation disabled, skipping trigger_ai_analysis");
        return;
      }
      if (eventPayload.application_id) {
        await supabase.functions.invoke("evaluate-candidate", {
          body: { application_id: eventPayload.application_id },
        });
      }
      break;

    default:
      console.warn(`[Automation] Ação desconhecida: ${actionType}`);
  }
}

/**
 * Main dispatcher: call this after any relevant mutation.
 */
export async function dispatchAutomationEvent(eventName: string, payload: Record<string, any> = {}) {
  try {
    const config = await getAutomationConfig();
    if (!config.automation_enabled) return;

    // Check if the module associated with this event is enabled
    const moduleName = EVENT_TO_MODULE[eventName];
    if (moduleName) {
      const moduleEnabled = await checkFeatureEnabled(moduleName);
      if (!moduleEnabled) {
        console.log(`[Automation] Module "${moduleName}" disabled, skipping event "${eventName}"`);
        // Log the blocked attempt to activity_logs
        await logActivity({
          action: "module_blocked_by_flag",
          module: "feature_control",
          details: {
            module_name: moduleName,
            event_name: eventName,
            source: "automation_engine",
            payload,
            timestamp: new Date().toISOString(),
          },
        });
        return;

      }
    }

    // Register event via edge function (service_role writes; RLS blocks direct client INSERT)
    let eventId: string | null = null;
    try {
      const { data: eventRecord, error: regErr } = await supabase.functions.invoke(
        "automation-event",
        { body: { op: "register", event_name: eventName, payload } },
      );
      if (regErr) throw regErr;
      eventId = (eventRecord as any)?.id ?? null;
    } catch (insertErr) {
      console.warn("[Automation] Failed to register automation_event:", insertErr);
    }

    // Fetch active rules for this event
    const { data: rules } = await supabase
      .from("automation_rules" as any)
      .select("*")
      .eq("event_name", eventName)
      .eq("is_active", true)
      .order("priority");

    if (!rules || rules.length === 0) {
      // Mark event as processed even if no rules matched
      if (eventId) {
        await supabase.functions.invoke("automation-event", { body: { op: "mark_processed", id: eventId } });
      }
      return;
    }

    for (const rule of rules as any[]) {
      if (!evaluateCondition(rule.condition_json || {}, payload)) continue;

      let attempts = 0;
      const maxRetries = config.max_automation_retries;
      let success = false;
      let errorMsg: string | null = null;

      while (attempts < maxRetries && !success) {
        const start = Date.now();
        try {
          // P2: Use timeout enforcement via Promise.race
          await executeActionWithTimeout(
            rule.action_type,
            rule.action_payload || {},
            payload,
            config.automation_timeout_seconds,
            config,
          );
          success = true;
          const elapsed = Date.now() - start;
          await supabase.from("automation_logs" as any).insert({
            rule_id: rule.id,
            event_id: eventId,
            event_name: eventName,
            action_type: rule.action_type,
            action_result: "sucesso",
            execution_time_ms: elapsed,
            context: payload,
          } as any);
        } catch (err: any) {
          attempts++;
          errorMsg = err?.message || String(err);

          // P2: Exponential backoff before retry
          if (attempts < maxRetries) {
            const backoffMs = Math.min(1000 * Math.pow(2, attempts - 1), 10000);
            await sleep(backoffMs);
          }

          if (attempts >= maxRetries) {
            await supabase.from("automation_logs" as any).insert({
              rule_id: rule.id,
              event_id: eventId,
              event_name: eventName,
              action_type: rule.action_type,
              action_result: "falha",
              error_message: errorMsg,
              execution_time_ms: Date.now() - start,
              context: { ...payload, retry_count: attempts },
            } as any);

            // Notify admins about critical failure
            try {
              const { data: adminRoles } = await supabase
                .from("user_roles" as any)
                .select("user_id")
                .eq("role", "admin")
                .limit(10);
              for (const ar of (adminRoles || []) as any[]) {
                await supabase.from("notifications" as any).insert({
                  event_type: "automation_failure",
                  recipient_id: ar.user_id,
                  channel: "push",
                  title: "Falha em automação",
                  body: `Regra "${rule.description || rule.action_type}" falhou após ${attempts} tentativas: ${errorMsg}`,
                  status: "pending",
                  action_url: "/admin/configuracoes",
                  action_type: "alert",
                } as any);
              }
            } catch (notifErr) {
              console.error("[Automation] Falha ao notificar admins:", notifErr);
            }
          }
        }
      }
    }

    // Mark event as processed after all rules executed
    if (eventId) {
      await supabase.functions.invoke("automation-event", { body: { op: "mark_processed", id: eventId } });
    }
  } catch (err) {
    console.error("[Automation] Erro no dispatcher:", err);
  }
}
