export const EVENT_TYPE_LABELS: Record<string, string> = {
  test_assigned: "Novo teste disponível para você",
  documents_requested: "Hora de enviar seus documentos",
  document_rejected: "Um documento precisa ser reenviado",
  document_approved: "Documento aceito com sucesso ✅",
  document_uploaded: "Documento enviado com sucesso",
  document_deadline_reminder: "Lembrete: documentos pendentes",
  interview_scheduled: "Sua entrevista foi marcada",
  interview_cancelled: "Entrevista cancelada",
  interview_rescheduled: "Sua entrevista foi reagendada",
  interview_pending_approval: "Agendamento pendente de aprovação",
  interview_no_show: "Não comparecimento registrado",
  candidate_approved: "Parabéns, você foi aprovado! 🎉",
  candidate_rejected: "Atualização sobre sua candidatura",
  candidate_standby: "Você está na reserva de talentos",
  candidate_hired: "Você foi contratado! 🎉",
  phase_advanced: "Você avançou para a próxima etapa! 🎉",
  apto_para_vaga: "Você está apto para a vaga! 🎯",
  hiring_completed: "Bem-vindo à equipe! 🎉",
  candidate_dismissed: "Atualização sobre seu vínculo",
  faq_resposta: "Sua dúvida foi respondida",
  candidate_liked: "Um recrutador se interessou pelo seu perfil",
  candidate_paused: "Sua candidatura foi pausada",
  test_submitted: "Teste enviado com sucesso",
  new_application: "Nova candidatura recebida",
  candidate_withdrawn: "Candidatura cancelada",
  reschedule_requested: "Solicitação de reagendamento",
  job_closed: "Vaga encerrada",
  job_request_created: "Nova solicitação de vaga criada",
  job_request_em_analise: "Sua solicitação de vaga está em análise",
  job_request_aprovada: "Solicitação de vaga aprovada ✅",
  job_request_reprovada: "Solicitação de vaga não aprovada",
  automation_reminder: "Lembrete automático",
  automation_failure: "Falha em automação",
  migration_completed: "Migração de dados concluída",
  talent_pool_auto_added: "Seu perfil foi adicionado ao Banco de Talentos",
  talent_invite_sent: "Convite para Processo Seletivo",
  talent_invite_accepted: "Convite aceito pelo candidato",
  talent_invite_declined: "Convite recusado pelo candidato",
  address_change: "Endereço atualizado",
  interview_reminder_24h: "Sua entrevista é amanhã!",
  interview_reminder_2h: "Sua entrevista começa em 2 horas",
  interview_reminder_1h: "Sua entrevista começa em 1 hora",
  interview_reminder_15min: "Faltam 15 minutos para sua entrevista",
  interview_reminder_10min: "Faltam 10 minutos para sua entrevista",
  interview_reminder: "Lembrete: você tem uma entrevista em breve",
  voice_interview_started: "Entrevista com IA iniciada",
  voice_interview_failed: "Entrevista com IA encerrada",
  interview_approved: "Aprovado na entrevista! 🎉",
  interview_talent_pool: "Entrevista concluída — Banco de Talentos",
  interview_escalated: "Entrevista em análise por recrutador",
  interview_completed: "Entrevista concluída",
  voice_interview_completed: "Entrevista com IA concluída",
  triage_stage_fail: "Dicas para melhorar nas perguntas iniciais",
  interview_escalated_admin: "Entrevista IA requer revisão humana",
  corporate_job_created: "Nova vaga corporativa criada",
  cargo_alterado: "Cargo atualizado",
  unit_job_stalled: "Alerta: vaga estagnada",
  unit_high_rejection: "Alerta: alta taxa de rejeição",
  unit_high_withdrawal: "Alerta: alta taxa de desistência",
  weekly_monitoring_report: "Relatório semanal de monitoramento",
  candidato_apto_no_raio: "Candidato disponível na região",
  ai_prompt_created: "Novo prompt de IA criado",
  ai_prompt_activated: "Prompt de IA ativado",
  pipeline_version_change: "Pipeline atualizado",
  pipeline_phasecompleted: "Fase do pipeline concluída",
  pipeline_phasefailed: "Falha na fase do pipeline",
  pipeline_highscore: "Score alto no pipeline",
  channel_failure: "Falha de canal de comunicação",
};
